# Generated by Django 5.2.17 on 2026-08-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlaudit', '0002_datasource_db_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryorder',
            name='schema',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Schema'),
        ),
        migrations.AddField(
            model_name='sqlorder',
            name='schema',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Schema'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('mongodb', 'MongoDB'), ('polardb', 'PolarDB'), ('sqlserver', 'SQL Server')], default='mysql', max_length=16, verbose_name='数据库类型'),
        ),
    ]
